// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqhBbTiudduwch6EOevqSRcDbAojO-HlM',
    appId: '1:941317230359:web:17a4ab4c06d79aeffbf152',
    messagingSenderId: '941317230359',
    projectId: 'flutter-basics-1',
    authDomain: 'flutter-basics-1.firebaseapp.com',
    storageBucket: 'flutter-basics-1.firebasestorage.app',
    measurementId: 'G-CR28XNFL61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyomHXhPRIXhjsabtlJxlO5SvmnEjILfA',
    appId: '1:941317230359:android:09b970dbe0ca1fddfbf152',
    messagingSenderId: '941317230359',
    projectId: 'flutter-basics-1',
    storageBucket: 'flutter-basics-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmAupqjpEXZqfr6oWgksPeGsOe73WERzA',
    appId: '1:941317230359:ios:dd73ca84b6fc00d2fbf152',
    messagingSenderId: '941317230359',
    projectId: 'flutter-basics-1',
    storageBucket: 'flutter-basics-1.firebasestorage.app',
    iosBundleId: 'com.example.flutterBasics1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmAupqjpEXZqfr6oWgksPeGsOe73WERzA',
    appId: '1:941317230359:ios:dd73ca84b6fc00d2fbf152',
    messagingSenderId: '941317230359',
    projectId: 'flutter-basics-1',
    storageBucket: 'flutter-basics-1.firebasestorage.app',
    iosBundleId: 'com.example.flutterBasics1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqhBbTiudduwch6EOevqSRcDbAojO-HlM',
    appId: '1:941317230359:web:16305c4b69659ac1fbf152',
    messagingSenderId: '941317230359',
    projectId: 'flutter-basics-1',
    authDomain: 'flutter-basics-1.firebaseapp.com',
    storageBucket: 'flutter-basics-1.firebasestorage.app',
    measurementId: 'G-9X96J3K94M',
  );
}
